<?php

namespace AppBundle\Repository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDefaultRole(){
        $results = $this
            ->createQueryBuilder("role")
            ->andWhere('role.name like :user')
            ->setParameters([
                'user'=> '%USER%'
            ])
            ->setFirstResult(0)//a partir de 0
            ->setMaxResults(1)  //jusqu'au 10ieme resultat
            ->getQuery()
            ->getOneOrNullResult()//getArrayResult

        ;

        return $results;
    }
}
